"""
Django settings for resume_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#926!abk&*)@ps0xv7#oq)^@m8h2ad*7#(4d3c6adx#(_s-&v2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'resume_app',
    'corsheaders',
    'django.contrib.sites',
    'payments',
    'rest_framework',
    'django_extensions'

]

PAYMENT_VARIANTS = {
    'default': ('payments.dummy.DummyProvider', {}),
    'alipay': ('your_project.payments.AlipayProvider', {
        'app_id': 'your_alipay_app_id',
        'app_notify_url': 'your_notify_url',
        'app_private_key_path': 'path_to_your_private_key.pem',
        'alipay_public_key_path': 'path_to_alipay_public_key.pem',
        'return_url': 'your_return_url',
        'debug': True,  # 沙箱环境
    }),
    'wechat': ('your_project.payments.WeChatPayProvider', {
        'appid': 'your_wechat_appid',
        'mch_id': 'your_merchant_id',
        'api_key': 'your_api_key',
        'notify_url': 'your_notify_url',
    }),
    'stripe': ('payments.stripe.StripeProvider', {
        'secret_key': 'your_stripe_secret_key',
        'public_key': 'your_stripe_public_key',
    }),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "middleware.redis_middleware.RedisMiddleware",
    'resume_app.middleware.JWTAuthenticationMiddleware'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # 允许 React 本地开发环境访问
    "http://127.0.0.1:3000",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",  # ✅ 添加 PUT 方法
    "OPTIONS",
]


ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
]

CORS_ALLOW_CREDENTIALS = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'resume_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "resume_app" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resume_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "your-fallback-secret-key")

PAYMENT_HOST = "http://localhost:8000"  # 或者你的生产环境域名
SITE_ID = 1
APPEND_SLASH = False

# 限流策略
RATE_LIMIT_HOURLY = 10
RATE_LIMIT_DAILY = 30

# Redis 连接信息
REDIS_HOST = "localhost"
REDIS_PORT = 6379